title: Welcome # name of the site
author: Marcel Alexandru Nitan # name of site's author
email: nitan.marcel@gmail.com # email of site's author
url: https://nitanmarcel.com # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog"f the site, e.g. "/blog"
description: > # description of the site (multiple lines allowed)
  Fork of <a href="https://github.com/riggraz/no-style-please">riggraz/no-style-please</a>. Template modified to fit my needs on my <a href="https://nitanmarcel.com">website</a>
google_analytics: # Google analytics id

permalink: /:slug.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

theme: no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page
  avatar_url: "https://i.loli.net/2019/08/26/JzCLhDWPEybZr2T.jpg" # avatar in about page

    # generate social links in about page.
  social_links:
    # twitter: 
    github:  huangyz0918
    rss: RSS
    # dribbble: 
    facebook: huangyz0918
    # flickr:   
    # instagram: 
    linkedin: yizheng-huang
    # pinterest: 
    # youtube: 
    # youtube_channel: 
    # youtube_channel_name: 
    # telegram: 
    # googleplus: 
    # microdotblog: 
    # reddit: 

    # Mastodon instances
    # mastodon:
    # - username: 
    #   instance: 
    # - username: 
    #   instance: 

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-tidy
  - premonition